### ISSUE TITLE
shadejs overwrites `fetch` global

### ISSUE THREAD

**Issue by blake-regalia** [securesecrets/shadejs#107]
**Describe the bug**
The latest release breaks compatibility with node.js due to build changes that assume the environment is the browser and force node polyfills, overwriting the `fetch` global and leading to this error:

```
/node_modules/@shadeprotocol/shadejs/dist/index.js:10363
              var H = new XMLHttpRequest();
                      ^

ReferenceError: XMLHttpRequest is not defined
    at /node_modules/@shadeprotocol/shadejs/dist/index.js:10363:23
    at new Promise (<anonymous>)
    at A (/node_modules/@shadeprotocol/shadejs/dist/index.js:10359:20)
```

Inspecting `fetch` reveals the polyfill:
```
> fetch
<ref *1> [Function: A] {
  ponyfill: true,
  default: [Circular *1],
  fetch: [Circular *1],
  Headers: [Function: u],
  Request: [Function: T],
  Response: [Function: I] {
    error: [Function (anonymous)],
    redirect: [Function (anonymous)]
  }
}
```

**To Reproduce**
Try importing the ESM in node.js and attempt to perform `fetch()`.

**Expected behavior**
Don't overwrite globals in node.js environment. Should be exporting ESM and use the `"exports"` package.json feature.

**Comment by AustinWoetzel** [comment]
We are troubleshooting a similar problem with node.js environment right now, hopefully have a solution soon.

**Comment by AustinWoetzel** [comment]
Did versions 1.1.2 and earlier work for you, or do you see the same issue there?

**Comment by AustinWoetzel** [comment]
Please let us know if the above fix does not resolve your issues. It should as we removed the polyfill.
