### ISSUE TITLE
Error: bisect endpoints must have different signs

### ISSUE THREAD

**Issue by Subfortytwo** [securesecrets/shadejs#148]
Lately, I started to have a new error message:

```
Error: bisect endpoints must have different signs
    at fr (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:42061)
    at Et (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:42677)
    at Oe.findZeroWithPool1Params (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:50617)
    at Oe.solveInvFnForPool1Size (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:43889)
    at Oe.simulateToken0WithToken1Trade (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:45529)
    at Oe.swapToken0WithToken1 (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:44237)
    at yr (/home/user/gnagna/node_modules/@shadeprotocol/shadejs/dist/index.umd.cjs:3:52564)
    at main (/home/user/gnagna/src/test.ts:43:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

I am not sure 0o.

Here a piece of faulty code producing the error. BN is an alias for BigNumer and toHuman divides by 100000 the input:

```

const output = await batchQueryPairsInfo({
...
    })

    const u = output[0].pairInfo
    const humanVal = toHuman(BN(10000000))

    console.log("This is humanVal: ", humanVal.toString())
    if (!u.stableParams)
        return

    const inputParams = {
        inputToken0Amount: humanVal,
        inputToken1Amount: humanVal,

        poolToken0Amount: toHuman(BN(u.token0Amount)),
        poolToken1Amount: toHuman(BN(u.token1Amount)),
        priceRatio: BN(u.stableParams.priceRatio ?? 0),
        alpha: BN(u.stableParams.alpha),
        gamma1: BN(u.stableParams.gamma1),
        gamma2: BN(u.stableParams.gamma2),
        liquidityProviderFee: BN(u.lpFee),
        daoFee: BN(u.daoFee),
        minTradeSizeToken0For1: BN(u.stableParams.minTradeSizeXForY),
        minTradeSizeToken1For0: BN(u.stableParams.minTradeSizeYForX),
        priceImpactLimit: BN(u.stableParams.maxPriceImpactAllowed)
    };


    const quote_to_base = stableSwapToken0for1(inputParams).decimalPlaces(6)
```

Thanks for your support.

**Comment by AustinWoetzel** [comment]
I'm not sure, i've asked one of our stableswap experts on this. However I will say, this input is suspect.

`priceRatio: BN(u.stableParams.priceRatio ?? 0),` 

I don't think you'll be able to set this to zero when priceRatio isn't available.
