### ISSUE TITLE
stableSwapToken0for1/stableSwapToken1for0 sometimes crashes and gives wrong values.

### ISSUE THREAD

**Issue by Subfortytwo** [securesecrets/shadejs#84]
Here an example:

```
{
  id: 'dd5153f8-8a7b-48e5-a7fb-995a4afa4e62',
  contract: {
    address: 'secret1a65a9xgqrlsgdszqjtxhz069pgsh8h4a83hwt0',
    code_hash: 'e88165353d5d7e7847f2c84134c3f7871b2eee684ffac9fcf8d99a4da39dc2f2'
  },
  factory: 'c58ee40c-f86f-472b-b06e-3f649fbbdb70',
  token_0: '4787120a-8ff7-4cca-b64c-635467e68569',
  token_0_amount: '13301854821',
  token_1: 'baa6de5a-74aa-46a4-b9d0-f092441747b4',
  token_1_amount: '22105452634',
  lp_token: 'e4f8f87d-5d75-4f8a-bcb6-87a8281edfca',
  staking_contract: {
    id: '44919a1a-305b-48cb-9cd2-5d6d835359a2',
    address: 'secret1hh9kgm00kfcjc78kefsf29g0fvxnd3f2tt9lrs',
    code_hash: 'a83f0fdc6e5bcdb1f59e39200a084401309fc5338dbb2e54a2bcdc08fa3eaf49'
  },
  stable_params: {
    a: '150',
    gamma1: '6',
    gamma2: '50',
    min_trade_size_0_to_1: '0.0001',
    min_trade_size_1_to_0: '0.0001',
    max_price_impact_allowed: '1000',
    price_ratio: '1.2991729379900840424255648025'
  },
  volume: {
    volume: '7921070.012177731',
    volume_24h_change: '59765.703711636',
    volume_24h_change_perc: '53.3707961160127'
  },
  fees: { dao: '0.0005', lp: '0.0005' },
  liquidity: '17623480028',
  liquidity_usd: '385077.33433510864',
  apy: {
    total: 21.37461079001067,
    fee: 0.02607142857142857,
    reward_tokens: [ [Object] ]
  },
  apr: {
    total: 21.37461079001067,
    fee: 0.02607142857142857,
    reward_tokens: [ [Object] ]
  },
  currency: 'USD',
  flags: [ 'derivative', 'stable' ]
}

```

So I construct the object inputParams, with inputToken0Amount = 10000000 :

```
{
  inputToken0Amount: BigNumber { s: 1, e: 7, c: [ 10000000 ] },
  inputToken1Amount: BigNumber { s: 1, e: 7, c: [ 10000000 ] },
  poolToken0Amount: BigNumber { s: 1, e: 10, c: [ 13301854821 ] },
  poolToken1Amount: BigNumber { s: 1, e: 10, c: [ 22105452634 ] },
  priceRatio: BigNumber { s: 1, e: 0, c: [ 1, 29917293799008, 40424255648025 ] },
  alpha: BigNumber { s: 1, e: 2, c: [ 150 ] },
  gamma1: BigNumber { s: 1, e: 0, c: [ 6 ] },
  gamma2: BigNumber { s: 1, e: 1, c: [ 50 ] },
  liquidityProviderFee: BigNumber { s: 1, e: -4, c: [ 50000000000 ] },
  daoFee: BigNumber { s: 1, e: -4, c: [ 50000000000 ] },
  minTradeSizeToken0For1: BigNumber { s: 1, e: -4, c: [ 10000000000 ] },
  minTradeSizeToken1For0: BigNumber { s: 1, e: -4, c: [ 10000000000 ] },
  priceImpactLimit: BigNumber { s: 1, e: 3, c: [ 1000 ] }
}

```
` const x = stableSwapToken0for1(inputParams).decimalPlaces(0) -> 1121409767 ??????????????? `

```
const y = stableSwapToken1for0(inputParams).decimalPlaces(0) -> 

Shade error TypeError: Cannot read properties of undefined (reading 'isLessThanOrEqualTo')
    at StableConfig.calculateInvariant (/home/user/pop/node_modules/@shadeprotocol/shadejs/dist/shadejs.cjs:75:189749)
    at new StableConfig (/home/user/pop/node_modules/@shadeprotocol/shadejs/dist/shadejs.cjs:75:184987)
    at r (/home/user/pop/node_modules/@shadeprotocol/shadejs/dist/shadejs.cjs:75:195251)
    at stableSwapToken1for0 (/home/user/pop/node_modules/@shadeprotocol/shadejs/dist/shadejs.cjs:75:195422)
```

Hum, any help would be appreciated, thank you very much.

**Comment by AustinWoetzel** [comment]
Make sure inputs to the stable swap calculation are in human readable form meaning that you need to convert from uDenom. For example, if the pool liquidity is 1234567 uSCRT tokens, then you must input 1.234567 since scrt has 6 decimals.

**Comment by Subfortytwo** [comment]
Thanks for your quick answer !
There is still something I am not getting:
On the SHADE swap page, I am currently getting the following values:
```
1ATOM -> 0.777963 STatom
10Atom -> 7.779421
100Atom -> 77.773379
1000Atom -> 775.993412
10000Atom -> 7705.396907
```
```
 const arr = [1, 10, 100, 1000, 10000]
 arr.forEach(e => {inputParams.inputToken0Amount = BN(e); console.log("Value: ", e, ":", stableSwapToken0for1(inputParams).decimalPlaces(6).toString())})

```

Gives me the following output:

```
Value:  1 : 0.777966
Value:  10 : 7.779656
Value:  100 : 77.796564
Value:  1000 : 777.965635
Value:  10000 : 7779.656141
```

On the other hand, if I do it the wrong way, I am getting closer values:
```
const arr = [1, 10, 100, 1000, 10000]
arr.forEach(e => {inputParams.inputToken0Amount = BN(e).times(1000000); console.log("Value: ", e, ":", stableSwapToken0for1(inputParams).dividedBy(1000000).decimalPlaces(6).toString())})
         
```

The following values are exactly the same as the ShadeSwap page:
```
Value:  1 : 0.777963
Value:  10 : 7.779421
Value:  100 : 77.773379
Value:  1000 : 775.993412
Value:  10000 : 7705.396907

```

However, I multiplied by 1000000, which is not even a uDenom.

Thank you !

**Comment by Subfortytwo** [comment]
Hum,
the shade JSON is returning a uDenom for poolToken0Amount and poolToken1Amount.They need to be converted to human readable form as well, then everything works as expected. 

Thanks a lot for your help.
